#+TITLE:  Emacs Configuration File
#+AUTHOR: Rickard Sundin
#+EMAIL:  rickard@snart.nu

* Introduction
This is my =.emacs= file. It is written in org-mode thanks to [[http://www.howardism.org/][Howard Abrahams]].

* Installation
On MacOS, it is easy to install using [[http://brew.sh/][Homebrew]].

#+BEGIN_SRC sh
brew install emacs --with-cocoa --with-gnutls --with-librsvg --with-imagemagick
brew linkapps emacs
#+END_SRC

In order to be able to open Emacs super quick, run emacs as a service in the background, and use =emacsclient= to open editor windows.
#+BEGIN_SRC sh
brew services start emacs
#+END_SRC

* Basic appearance
For a clean appearance I remove the toolbar, menubar and scrollbars. I always
try to always use keyboard shortcuts anyways.

#+BEGIN_SRC elisp 
(tool-bar-mode -1)
(menu-bar-mode -1)
(scroll-bar-mode -1)
#+END_SRC

Usually I never want my computer to beep at me. The default visible bell 
draws a big warning sign with an exclamation mark in the middle of the frame.
I prefer [[http://stuff-things.net/2015/10/05/emacs-visible-bell-work-around-on-os-x-el-capitan/][this slick implementaion]] that flashes the mode line instead.

#+BEGIN_SRC elisp 
  (setq visible-bell nil)
  (setq ring-bell-function (lambda ()
                             (invert-face 'mode-line)
                             (run-with-timer 0.1 nil 'invert-face 'mode-line)))
#+END_SRC

Also remove the startup message and the message explaining the scratch buffer. 

#+BEGIN_SRC elisp
(setq inhibit-startup-message t)
(setq initial-scratch-message "")
#+END_SRC

I like to see the current column displayed on the mode line.

#+BEGIN_SRC elisp
(setq column-number-mode t)
#+END_SRC

Show time in the mode line, but do not show load.

#+BEGIN_SRC elisp
(setq display-time-24hr-format t)
(setq display-time-default-load-average nil)
(display-time-mode 1)
#+END_SRC

Show battery status in the mode line.

#+BEGIN_SRC elisp
(display-battery-mode 1)
#+END_SRC

* Directory structure

#+BEGIN_SRC elisp
  (defconst rs/emacs-directory (concat (getenv "HOME") "/.emacs.d/"))
  (defun rs/emacs-subdirectory (d) (expand-file-name d rs/emacs-directory))
#+END_SRC

#+BEGIN_SRC elisp
  (let* ((subdirs '("elisp" "backups" "snippets"))
         (fulldirs (mapcar (lambda (d) (rs/emacs-subdirectory d)) subdirs)))
    (dolist (dir fulldirs)
      (when (not (file-exists-p dir))
        (message "Make directory: %s" dir)
        (make-directory dir))))
#+END_SRC

* Backup files
Keep all backup files in one place.

#+BEGIN_SRC elisp 
  (setq backup-directory-alist
        `(("." . ,(expand-file-name
                   (rs/emacs-subdirectory "backups")))))
#+END_SRC

* Package management
Emacs, like any serious operating system, of course has its own [[https://elpa.gnu.org/][package management system]].

#+BEGIN_SRC elisp 
(require 'package)
(setq package-archives '(("gnu" . "https://elpa.gnu.org/packages/")
                         ("melpa" . "https://melpa.org/packages/")))
(package-initialize)
#+END_SRC

By installing use-package, package management and configuration is kept together which
gives better readabiltiy and maintainablility.

#+BEGIN_SRC elisp
  (unless (package-installed-p 'use-package)
    (package-refresh-contents)
    (package-install 'use-package))

  (require 'use-package)
#+END_SRC

* Load Path
This is where to find packages not available via package manager:

#+BEGIN_SRC elisp
(add-to-list 'load-path (rs/emacs-subdirectory "elisp"))
#+END_SRC

* Mac stuff
When launching a GUI application in MacOS it does not by default pick up
environment variables from =.profile=. Here is a solution.

#+BEGIN_SRC elisp 
  (use-package exec-path-from-shell
    :ensure t
    :config
    (when (memq window-system '(mac ns))
      (exec-path-from-shell-initialize)))
#+END_SRC

* Colors
I like to add the [[http://ethanschoonover.com/solarized][Solarized]] and [[http://kippura.org/zenburnpage/][Zenburn]] color themes. Use =M-x load-theme=
to switch theme, or =M-x disable-theme= to go back to the default theme.

#+BEGIN_SRC elisp 
  (use-package zenburn-theme
    :ensure t)
  (use-package solarized-theme
    :ensure t
    :config
    (load-theme 'zenburn t)
    (custom-theme-set-faces
     'zenburn `(org-todo ((t (:bold t :foreground "#CC9393" :background "#3F3F3F" :weight bold))))))
#+END_SRC

* Fonts
Adobes [[https://github.com/adobe-fonts/source-code-pro][Source Code Pro]] is a nice font.

#+BEGIN_SRC elisp 
(add-to-list 'default-frame-alist '(font . "Source Code Pro 14"))
(when (display-graphic-p nil)
  (set-face-attribute 'default t :font "Source Code Pro 14"))
#+END_SRC

* Vim
My fingers like using the Vim navigation model, so that they don't have to leave
the home row ('asdf' 'jkl;') that much. Queue [[https://www.emacswiki.org/emacs/Evil][Evil-mode]]

#+BEGIN_SRC elisp 
  (use-package evil
    :ensure t
    :config
    (evil-mode 1))
#+END_SRC

* Which key?
[[https://github.com/justbur/emacs-which-key][Which-key]] helps to improve my shortcut knowledge.
#+BEGIN_SRC elisp
(use-package which-key
  :ensure t
  :diminish which-key-mode
  :init
  (which-key-mode))

#+END_SRC

When it is installed, I can type a partial command sequence, for exampel =C-x=, and after one second a list of all keyboard shortcuts
starting with that sequence is presented.

If there are more commands than will fit in the buffer window, is is possible to press =C-h n= to go to the next page and =C-h p= to go back again.

* Undo tree
[[https://www.emacswiki.org/emacs/UndoTree][Undo-tree]] allows you to recover any past state of a buffer.

#+BEGIN_SRC elisp
(use-package undo-tree
  :ensure t
  :diminish undo-tree-mode)
#+END_SRC

* Helm 
[[https://emacs-helm.github.io/helm/][Helm]] is an incremental completion and selection narrowing framework that (amongst
other things) makes it easier to find files and directories.

#+BEGIN_SRC elisp 
  (use-package helm
    :ensure t
    :diminish helm-mode
    :config
    (require 'helm-config)
    (helm-mode 1)
    (helm-autoresize-mode 1)
    (define-key global-map [remap find-file] 'helm-find-files)
    (define-key global-map [remap occur] 'helm-occur)
    (define-key global-map [remap list-buffers] 'helm-buffers-list)
    (define-key global-map [remap dabbrev-expand] 'helm-dabbrev)
    (global-set-key (kbd "M-x") 'helm-M-x)
    (define-key helm-map (kbd "<tab>") 'helm-execute-persistent-action)
    (define-key helm-map (kbd "C-i") 'helm-execute-persistent-action)
    (define-key helm-map (kbd "C-z")  'helm-select-action)
    (global-set-key (kbd "M-y") 'helm-show-kill-ring))
#+END_SRC

[[https://github.com/ggreer/the_silver_searcher][The Silver Searcher]] is a useful tool to search quickly in multiple files.

First it needs to be installed on your system.
#+BEGIN_SRC sh :tangle no
brew install the_silver_searcher
#+END_SRC

Then we install helm-ag.
#+BEGIN_SRC elisp
(use-package helm-ag
:ensure t)
#+END_SRC

* Projectile
[[http://batsov.com/projectile/][Projectile]] is a project navigation and management library.

#+BEGIN_SRC elisp
  (use-package projectile
    :ensure t
    :config
    (projectile-global-mode)
    (setq projectile-mode-line
      '(:eval (if (file-remote-p default-directory)
                  " Projectile"
                  (format " [%s]" (projectile-project-name))))))

  (use-package helm-projectile
    :ensure t
    :config
    (helm-projectile-on))
#+END_SRC

* Calendar
I like my weeks to start on Mondays.

#+BEGIN_SRC elisp 
;; Calendar
(setq calendar-week-start-day 1)
#+END_SRC

* Git
Starting to get the hang of using Git through Magit.
If you only copy one thing from this file, this is probably it.

#+BEGIN_SRC elisp 
  (use-package magit
    :ensure t
    :bind
    ("C-x g" . magit-status)
    :config
    (setq magit-display-buffer-function #'magit-display-buffer-fullframe-status-v1)
    (setq magit-last-seen-setup-instructions "1.4.0"))
#+END_SRC

* Org-mode
If you don't use Emacs for anything else, you should at least use Org-mode.
** Basic appearance
Fold headers when a document is opened.
#+BEGIN_SRC elisp
  (setq org-startup-indented t)
#+END_SRC

Each codeblock should be coloured and indented according to its own language rules.
#+BEGIN_SRC elisp
   (setq org-src-fontify-natively t)
#+END_SRC

** Bullets
This packages displayes the asterisks in front of headers as nice UTF-8 bullets.
 
#+BEGIN_SRC elisp 
  (use-package org-bullets
    :ensure t
    :config
    (add-hook 'org-mode-hook 'org-bullets-mode))
#+END_SRC

** Tasks
#+BEGIN_SRC elisp 
  (setq org-log-done t)

  (setq org-todo-keywords
        '((sequence "TODO(t)" "DOING(i)" "WAITING(w)" "|" "DONE(d)" "CANCELED(c)")))

  (setq-local todo-keywords
              `(("^\\*+ \\(TODO\\) " 
                 (1 (progn (compose-region (match-beginning 1) (match-end 1) "☐")
                           nil)))
                ("^\\*+ \\(DOING\\) "
                 (1 (progn (compose-region (match-beginning 1) (match-end 1) "➙")
                           nil)))
                ("^\\*+ \\(WAITING\\) "
                 (1 (progn (compose-region (match-beginning 1) (match-end 1) "⌛")
                           nil)))
                ("^\\*+ \\(CANCELED\\) "
                 (1 (progn (compose-region (match-beginning 1) (match-end 1) "×")
                           nil)))
                ("^\\(CLOCK:\\)"
                 (1 (progn (compose-region (match-beginning 1) (match-end 1) "◉")
                           nil)))
                ("^\\*+ \\(DONE\\) "
                 (1 (progn (compose-region (match-beginning 1) (match-end 1) "☑")
                           nil)))))

  (font-lock-add-keywords 'org-mode todo-keywords)
  (font-lock-add-keywords 'org-journal-mode todo-keywords)
#+END_SRC

** Agenda
The agenda gives you an overview of org-mode tasks and deadlines.

#+BEGIN_SRC elisp 
  (define-key global-map "\C-ca" 'org-agenda)
  (setq org-agenda-files '("~/Documents/org" "~/Documents" "~"))
#+END_SRC

** Babel
[[http://plantuml.com][Plantuml]] is useful for creating simple diagrams.

#+BEGIN_SRC elisp
  (org-babel-do-load-languages
   'org-babel-load-languages
   '(;; other Babel languages
     (plantuml . t)))

  (setq org-plantuml-jar-path
        (expand-file-name "/usr/local/Cellar/plantuml/8048/plantuml.8048.jar"))
#+END_SRC

** Exporting
It is really easy to export (shortcut =C-c C-e=) an org-mode document as HTML, PDF or other formats.
#+BEGIN_SRC elisp
  (setq org-export-html-style-include-scripts nil
        org-export-html-style-include-default nil
        org-export-html-style
        "<link rel=\"stylesheet\" type=\"text/css\" href=\"org-style.css\" />")

#+END_SRC

Module [[https://github.com/marsmining/ox-twbs][ox-twbs]] can export org-mode docs as HTML compatible with Twitter Bootstrap.
#+BEGIN_SRC elisp
  (use-package ox-twbs
    :ensure t)
#+END_SRC

Module [[https://github.com/yjwen/org-reveal][org-reveal]] can export org-mode documents to reveal.js presentations. 
#+BEGIN_SRC elisp
  (use-package ox-reveal
    :ensure t)
#+END_SRC

* Journal
I will try out org-journal for journaling.

#+BEGIN_SRC elisp 
  (use-package org-journal
    :ensure t
    :config
    (setq org-journal-date-format "%Y-%m-%d, %a"))
#+END_SRC

* Gpg
Sometimes I need to read the value of =$SSH_AUTH_SOCK= from the path
to be able to use GPG properly from Emacs.

#+BEGIN_SRC elisp
(defun refresh-ssh-auth-sock ()
  "Read env variable SSH_AUTH_SOCK from path"
  (interactive)
  (exec-path-from-shell-copy-env "SSH_AUTH_SOCK"))
(define-key global-map "\C-cg" 'refresh-ssh-auth-sock)
#+END_SRC

* Snippets
[[https://github.com/capitaomorte/yasnippet][Yasnippets]] lets you define and insert snippets of text or code.

#+BEGIN_SRC elisp
(use-package yasnippet
  :ensure t
  :diminish yas-minor-mode
  :init
  (yas-global-mode 1)
  :config
  (add-to-list 'yas-snippet-dirs (locate-user-emacs-file "snippets")))
#+END_SRC

* General software development
Some features are useful for all computer langugages.

Company provides in-buffer completion.
#+BEGIN_SRC elisp
  (use-package company
    :ensure t
    :diminish company-mode
    :config
    (add-hook 'after-init-hook 'global-company-mode))
#+END_SRC

Flycheck provides on-the-fly syntax checking.
#+BEGIN_SRC elisp
  (use-package flycheck
    :ensure t
    :diminish flycheck-mode
    :config
    (add-hook 'after-init-hook #'global-flycheck-mode))
#+END_SRC

* Clojure
See [[file:clojure.org][clojure.org]] for details on my Clojure setup.

#+BEGIN_SRC elisp
(require 'init-clojure)
#+END_SRC

* Haskell
See [[file:haskell.org][haskell.org]] for details on my Haskell setup.

#+BEGIN_SRC elisp
(require 'init-haskell)
#+END_SRC

* Javascript
#+BEGIN_SRC elisp
(setq js-indent-level 2)
#+END_SRC

* HTML
[[https://github.com/smihica/emmet-mode][Emmet-mode]] is useful whenever you quickly need to type some HTML.
Autostart it on any markup modes

#+BEGIN_SRC elisp
(use-package emmet-mode
:ensure t
:config
(add-hook 'sgml-mode-hook 'emmet-mode))
#+END_SRC

* Restclient
Mode to use Emacs as a REST client.
#+BEGIN_SRC elisp
(use-package restclient
  :ensure t)
#+END_SRC

#+PROPERTY: header-args:sh  :tangle no
#+PROPERTY: header-args:elisp :tangle ~/.emacs.d/init.el
#+PROPERTY: results silent
#+PROPERTY: eval no-export
#+PROPERTY: comments org 
#+OPTIONS:  num:nil toc:nil todo:nil tasks:nil tags:nil
#+OPTIONS:  skip:nil author:nil email:nil creator:nil tim
